spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/MediaProject
    username: root
    password: alqud410
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none


springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  show-actuator: true

# s3
cloud:
  aws:
    credentials:
      accessKey: AKIAW4MVDSOLE55M4R75
      secretKey: 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
    s3:
      bucket: media-project-openlut
    region:
      static: ap-northeast-2
    stack:
      auto: false
#  group-configs:
#  - group: stores
#    paths-to-match: /store/**
#  - group: users
#    packages-to-scan: org.springdoc.demo.app2





#spring.datasource.url=jdbc:mysql://localhost:3306/MediaProject
#spring.datasource.username=root
#spring.datasource.password=alqud410
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database=mysql
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create
#springdoc.api-docs.path= /api-docs
#springdoc.default-consumes-media-type= application/json
#springdoc.default-produces-media-type= application/json
#springdoc.swagger-ui.operations-sorter=alpha